// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../index.js";

/**
 * @example
 *     {
 *         agentName: "agent_name",
 *         manifest: {
 *             task: "task",
 *             trigger: {
 *                 kind: "kind",
 *                 sourceId: "source_id",
 *                 type: "event"
 *             }
 *         },
 *         name: "name"
 *     }
 */
export interface CreateAutomationRequest {
    agentName: TrueForge.ResourceName;
    manifest: TrueForge.AutomationManifest;
    name: TrueForge.ResourceName;
}
