// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         eventId: "event_id"
 *     }
 */
export interface ReplayAutomationRequest {
    /** Ledger event to replay. */
    eventId: string;
}
