// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface AutomationRun {
    automationId: string;
    createdAt: Date;
    createdBySubject: TrueForge.CreatedBySubject;
    /** Ledger events coalesced into this run, oldest first. */
    eventIds: string[];
    finishedAt: Date | null;
    id: string;
    laneKey: string | null;
    mode: TrueForge.AutomationMode;
    /** Terminal details: required actions for a shadowed run, emitted event ids, or the error. */
    outcome: Record<string, unknown> | null;
    /** When the coalesce window closes and the run may start. */
    scheduledFor: Date;
    sessionId: string | null;
    status: TrueForge.AutomationRunStatus;
    subjectKey: string;
    triggeredAt: Date | null;
    updatedAt: Date;
}
