// This file was auto-generated by Fern from our API Definition.

export const AutomationStatus = {
    Active: "active",
    Paused: "paused",
} as const;
export type AutomationStatus = (typeof AutomationStatus)[keyof typeof AutomationStatus];
