// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface Automation {
    agentName: TrueForge.ResourceName;
    createdAt: Date;
    createdBySubject: TrueForge.CreatedBySubject;
    id: string;
    manifest: TrueForge.AutomationManifest;
    name: TrueForge.ResourceName;
    updatedAt: Date;
}
