// This file was auto-generated by Fern from our API Definition.

export const AutomationMode = {
    Shadow: "shadow",
    Armed: "armed",
} as const;
export type AutomationMode = (typeof AutomationMode)[keyof typeof AutomationMode];
