// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface AutomationManifest {
    /** Events about one subject arriving within this window share one run. */
    coalesceSeconds?: number;
    /** Event kinds written to the internal source when a run completes. */
    emit?: string[];
    /** Runs with the same rendered lane key execute one at a time. Empty = no lane. */
    lane?: TrueForge.LanePart[];
    mode?: TrueForge.AutomationMode;
    status?: TrueForge.AutomationStatus;
    /** First user message sent to the agent. The coalesced events are appended as JSON. */
    task: string;
    trigger: TrueForge.ComponentsSchemasEventTrigger;
}
