// This file was auto-generated by Fern from our API Definition.

export const AutomationRunStatus = {
    Coalescing: "coalescing",
    Triggered: "triggered",
    Waiting: "waiting",
    Completed: "completed",
    Shadowed: "shadowed",
    Failed: "failed",
} as const;
export type AutomationRunStatus = (typeof AutomationRunStatus)[keyof typeof AutomationRunStatus];
