// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface Condition {
    /** Dotted path into the event payload, e.g. `label.name`. */
    field: string;
    op: TrueForge.ConditionOperator;
    value?: TrueForge.ConditionValue;
}
