// This file was auto-generated by Fern from our API Definition.

export const ConditionOperator = {
    Eq: "eq",
    Neq: "neq",
    In: "in",
    NotIn: "not_in",
    Contains: "contains",
    Exists: "exists",
    NotExists: "not_exists",
} as const;
export type ConditionOperator = (typeof ConditionOperator)[keyof typeof ConditionOperator];
