// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

/**
 * Comparison value; omitted for `exists` / `not_exists`.
 */
export type ConditionValue = string | number | boolean | TrueForge.ConditionValueThreeItem[];
