// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface EventDetail {
    /** Provider delivery id; unique per source. */
    deliveryId: string;
    id: string;
    /** Connector event kind, e.g. `issues.labeled`. */
    kind: string;
    /** Raw provider payload as delivered. */
    payload: Record<string, unknown>;
    receivedAt: Date;
    /** When the coalesce loop matched this event against automations. */
    routedAt: Date | null;
    sourceId: string;
    sourceKind: TrueForge.EventSourceKind;
    /** Stable key of the thing the event is about, e.g. `owner/repo#61`. */
    subjectKey: string;
    summary: TrueForge.EventSummary;
}
