// This file was auto-generated by Fern from our API Definition.

export interface EventSummary {
    /** Login of the user or App that caused the event. */
    actor: string | null;
    /** Label name for label events. */
    label: string | null;
    /** Issue or pull request number when applicable. */
    number: number | null;
    /** `owner/repo` when the event belongs to a repository. */
    repository: string | null;
    /** Issue, pull request, or commit title when applicable. */
    title: string | null;
}
