// This file was auto-generated by Fern from our API Definition.

export const EventSourceStatus = {
    Pending: "pending",
    Active: "active",
    Error: "error",
} as const;
export type EventSourceStatus = (typeof EventSourceStatus)[keyof typeof EventSourceStatus];
