// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface EventSource {
    createdAt: Date;
    createdBySubject: TrueForge.CreatedBySubject;
    id: string;
    kind: TrueForge.EventSourceKind;
    lastDeliveryAt: Date | null;
    manifest: TrueForge.EventSourceManifest;
    name: TrueForge.ResourceName;
    status: TrueForge.EventSourceStatus;
    updatedAt: Date;
    /** URL GitHub delivers webhooks to for this source. */
    webhookUrl: string;
}
