// This file was auto-generated by Fern from our API Definition.

export const EventSourceKind = {
    Github: "github",
    Trueforge: "trueforge",
} as const;
export type EventSourceKind = (typeof EventSourceKind)[keyof typeof EventSourceKind];
