// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface EventTrigger {
    /** Connector event kind, e.g. `issues.labeled`. */
    kind: string;
    /** Event source the events come from. */
    sourceId: string;
    type: "event";
    when?: TrueForge.When;
}
