// This file was auto-generated by Fern from our API Definition.

export interface GithubAppConfig {
    /** GitHub App id. */
    appId: number;
    /** GitHub App URL slug. */
    appSlug: string;
    /** GitHub App OAuth client id. */
    clientId: string;
    /** Settings page of the App on GitHub. */
    htmlUrl: string;
    /** Login of the org or user that owns the App. */
    owner: string | null;
}
