// This file was auto-generated by Fern from our API Definition.

export interface GithubManifestStart {
    actionUrl: string;
    /** GitHub App manifest, POSTed as the `manifest` form field. */
    manifest: Record<string, unknown>;
    sourceId: string;
    state: string;
}
