// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface ListEventsResponse {
    data: TrueForge.Event[];
    pagination: TrueForge.TokenPagination;
}
