// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface ListAutomationsResponse {
    data: TrueForge.Automation[];
    pagination: TrueForge.TokenPagination;
}
