// This file was auto-generated by Fern from our API Definition.

import * as TrueForgeTypes from "../../src/api/index";
import { TrueForge } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AutomationsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    agent_name: "agent_name",
                    created_at: "2024-01-15T09:30:00Z",
                    created_by_subject: {
                        subject_display_name: "subject_display_name",
                        subject_id: "subject_id",
                        subject_type: "subject_type",
                    },
                    id: "id",
                    manifest: { task: "task", trigger: { kind: "kind", source_id: "source_id", type: "event" } },
                    name: "name",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            pagination: { limit: 1, next_page_token: "next_page_token", previous_page_token: "previous_page_token" },
        };

        server
            .mockEndpoint({ once: false })
            .get("/api/v1/automations")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            data: [
                {
                    agentName: "agent_name",
                    createdAt: new Date("2024-01-15T09:30:00.000Z"),
                    createdBySubject: {
                        subjectDisplayName: "subject_display_name",
                        subjectId: "subject_id",
                        subjectType: "subject_type",
                    },
                    id: "id",
                    manifest: {
                        task: "task",
                        trigger: {
                            kind: "kind",
                            sourceId: "source_id",
                            type: "event",
                        },
                    },
                    name: "name",
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                },
            ],
            pagination: {
                limit: 1,
                nextPageToken: "next_page_token",
                previousPageToken: "previous_page_token",
            },
        };
        const page = await client.automations.list();

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/automations")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.automations.list();
        }).rejects.toThrow(TrueForgeTypes.BadRequestError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            agent_name: "agent_name",
            manifest: { task: "task", trigger: { kind: "kind", source_id: "source_id", type: "event" } },
            name: "name",
        };
        const rawResponseBody = {
            data: {
                agent_name: "agent_name",
                created_at: "2024-01-15T09:30:00Z",
                created_by_subject: {
                    subject_display_name: "subject_display_name",
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                },
                id: "id",
                manifest: {
                    coalesce_seconds: 1,
                    emit: ["emit"],
                    lane: [{ path: "path", type: "field" }],
                    mode: "shadow",
                    status: "active",
                    task: "task",
                    trigger: { kind: "kind", source_id: "source_id", type: "event" },
                },
                name: "name",
                updated_at: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/api/v1/automations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.automations.create({
            agentName: "agent_name",
            manifest: {
                task: "task",
                trigger: {
                    kind: "kind",
                    sourceId: "source_id",
                    type: "event",
                },
            },
            name: "name",
        });
        expect(response).toEqual({
            data: {
                agentName: "agent_name",
                createdAt: new Date("2024-01-15T09:30:00.000Z"),
                createdBySubject: {
                    subjectDisplayName: "subject_display_name",
                    subjectId: "subject_id",
                    subjectType: "subject_type",
                },
                id: "id",
                manifest: {
                    coalesceSeconds: 1,
                    emit: ["emit"],
                    lane: [
                        {
                            path: "path",
                            type: "field",
                        },
                    ],
                    mode: "shadow",
                    status: "active",
                    task: "task",
                    trigger: {
                        kind: "kind",
                        sourceId: "source_id",
                        type: "event",
                    },
                },
                name: "name",
                updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            agent_name: "xy",
            manifest: { task: "x", trigger: { kind: "x", source_id: "x", type: "event" } },
            name: "xy",
        };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/api/v1/automations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.automations.create({
                agentName: "xy",
                manifest: {
                    task: "x",
                    trigger: {
                        kind: "x",
                        sourceId: "x",
                        type: "event",
                    },
                },
                name: "xy",
            });
        }).rejects.toThrow(TrueForgeTypes.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            agent_name: "xy",
            manifest: { task: "x", trigger: { kind: "x", source_id: "x", type: "event" } },
            name: "xy",
        };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/api/v1/automations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.automations.create({
                agentName: "xy",
                manifest: {
                    task: "x",
                    trigger: {
                        kind: "x",
                        sourceId: "x",
                        type: "event",
                    },
                },
                name: "xy",
            });
        }).rejects.toThrow(TrueForgeTypes.NotFoundError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            agent_name: "xy",
            manifest: { task: "x", trigger: { kind: "x", source_id: "x", type: "event" } },
            name: "xy",
        };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/api/v1/automations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.automations.create({
                agentName: "xy",
                manifest: {
                    task: "x",
                    trigger: {
                        kind: "x",
                        sourceId: "x",
                        type: "event",
                    },
                },
                name: "xy",
            });
        }).rejects.toThrow(TrueForgeTypes.ConflictError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: {
                agent_name: "agent_name",
                created_at: "2024-01-15T09:30:00Z",
                created_by_subject: {
                    subject_display_name: "subject_display_name",
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                },
                id: "id",
                manifest: {
                    coalesce_seconds: 1,
                    emit: ["emit"],
                    lane: [{ path: "path", type: "field" }],
                    mode: "shadow",
                    status: "active",
                    task: "task",
                    trigger: { kind: "kind", source_id: "source_id", type: "event" },
                },
                name: "name",
                updated_at: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .get("/api/v1/automations/automation_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.automations.get("automation_id");
        expect(response).toEqual({
            data: {
                agentName: "agent_name",
                createdAt: new Date("2024-01-15T09:30:00.000Z"),
                createdBySubject: {
                    subjectDisplayName: "subject_display_name",
                    subjectId: "subject_id",
                    subjectType: "subject_type",
                },
                id: "id",
                manifest: {
                    coalesceSeconds: 1,
                    emit: ["emit"],
                    lane: [
                        {
                            path: "path",
                            type: "field",
                        },
                    ],
                    mode: "shadow",
                    status: "active",
                    task: "task",
                    trigger: {
                        kind: "kind",
                        sourceId: "source_id",
                        type: "event",
                    },
                },
                name: "name",
                updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/automations/automation_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.automations.get("automation_id");
        }).rejects.toThrow(TrueForgeTypes.ForbiddenError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/automations/automation_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.automations.get("automation_id");
        }).rejects.toThrow(TrueForgeTypes.NotFoundError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            manifest: { task: "task", trigger: { kind: "kind", source_id: "source_id", type: "event" } },
            name: "name",
        };
        const rawResponseBody = {
            data: {
                agent_name: "agent_name",
                created_at: "2024-01-15T09:30:00Z",
                created_by_subject: {
                    subject_display_name: "subject_display_name",
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                },
                id: "id",
                manifest: {
                    coalesce_seconds: 1,
                    emit: ["emit"],
                    lane: [{ path: "path", type: "field" }],
                    mode: "shadow",
                    status: "active",
                    task: "task",
                    trigger: { kind: "kind", source_id: "source_id", type: "event" },
                },
                name: "name",
                updated_at: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .put("/api/v1/automations/automation_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.automations.update("automation_id", {
            manifest: {
                task: "task",
                trigger: {
                    kind: "kind",
                    sourceId: "source_id",
                    type: "event",
                },
            },
            name: "name",
        });
        expect(response).toEqual({
            data: {
                agentName: "agent_name",
                createdAt: new Date("2024-01-15T09:30:00.000Z"),
                createdBySubject: {
                    subjectDisplayName: "subject_display_name",
                    subjectId: "subject_id",
                    subjectType: "subject_type",
                },
                id: "id",
                manifest: {
                    coalesceSeconds: 1,
                    emit: ["emit"],
                    lane: [
                        {
                            path: "path",
                            type: "field",
                        },
                    ],
                    mode: "shadow",
                    status: "active",
                    task: "task",
                    trigger: {
                        kind: "kind",
                        sourceId: "source_id",
                        type: "event",
                    },
                },
                name: "name",
                updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            },
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            manifest: { task: "x", trigger: { kind: "x", source_id: "x", type: "event" } },
            name: "xy",
        };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/automations/automation_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.automations.update("automation_id", {
                manifest: {
                    task: "x",
                    trigger: {
                        kind: "x",
                        sourceId: "x",
                        type: "event",
                    },
                },
                name: "xy",
            });
        }).rejects.toThrow(TrueForgeTypes.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            manifest: { task: "x", trigger: { kind: "x", source_id: "x", type: "event" } },
            name: "xy",
        };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/automations/automation_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.automations.update("automation_id", {
                manifest: {
                    task: "x",
                    trigger: {
                        kind: "x",
                        sourceId: "x",
                        type: "event",
                    },
                },
                name: "xy",
            });
        }).rejects.toThrow(TrueForgeTypes.ForbiddenError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            manifest: { task: "x", trigger: { kind: "x", source_id: "x", type: "event" } },
            name: "xy",
        };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/automations/automation_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.automations.update("automation_id", {
                manifest: {
                    task: "x",
                    trigger: {
                        kind: "x",
                        sourceId: "x",
                        type: "event",
                    },
                },
                name: "xy",
            });
        }).rejects.toThrow(TrueForgeTypes.NotFoundError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = {
            manifest: { task: "x", trigger: { kind: "x", source_id: "x", type: "event" } },
            name: "xy",
        };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/automations/automation_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.automations.update("automation_id", {
                manifest: {
                    task: "x",
                    trigger: {
                        kind: "x",
                        sourceId: "x",
                        type: "event",
                    },
                },
                name: "xy",
            });
        }).rejects.toThrow(TrueForgeTypes.ConflictError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/automations/automation_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.automations.delete("automation_id");
        expect(response).toEqual({});
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .delete("/api/v1/automations/automation_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.automations.delete("automation_id");
        }).rejects.toThrow(TrueForgeTypes.ForbiddenError);
    });

    test("replay (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = { event_id: "event_id" };
        const rawResponseBody = {
            data: {
                automation_id: "automation_id",
                created_at: "2024-01-15T09:30:00Z",
                created_by_subject: {
                    subject_display_name: "subject_display_name",
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                },
                event_ids: ["event_ids"],
                finished_at: "2024-01-15T09:30:00Z",
                id: "id",
                lane_key: "lane_key",
                mode: "shadow",
                outcome: { key: "value" },
                scheduled_for: "2024-01-15T09:30:00Z",
                session_id: "session_id",
                status: "coalescing",
                subject_key: "subject_key",
                triggered_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/api/v1/automations/automation_id/replay")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.automations.replay("automation_id", {
            eventId: "event_id",
        });
        expect(response).toEqual({
            data: {
                automationId: "automation_id",
                createdAt: new Date("2024-01-15T09:30:00.000Z"),
                createdBySubject: {
                    subjectDisplayName: "subject_display_name",
                    subjectId: "subject_id",
                    subjectType: "subject_type",
                },
                eventIds: ["event_ids"],
                finishedAt: new Date("2024-01-15T09:30:00.000Z"),
                id: "id",
                laneKey: "lane_key",
                mode: "shadow",
                outcome: {
                    key: "value",
                },
                scheduledFor: new Date("2024-01-15T09:30:00.000Z"),
                sessionId: "session_id",
                status: "coalescing",
                subjectKey: "subject_key",
                triggeredAt: new Date("2024-01-15T09:30:00.000Z"),
                updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            },
        });
    });

    test("replay (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = { event_id: "x" };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/api/v1/automations/automation_id/replay")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.automations.replay("automation_id", {
                eventId: "x",
            });
        }).rejects.toThrow(TrueForgeTypes.BadRequestError);
    });

    test("replay (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = { event_id: "x" };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/api/v1/automations/automation_id/replay")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.automations.replay("automation_id", {
                eventId: "x",
            });
        }).rejects.toThrow(TrueForgeTypes.ForbiddenError);
    });

    test("replay (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = { event_id: "x" };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/api/v1/automations/automation_id/replay")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.automations.replay("automation_id", {
                eventId: "x",
            });
        }).rejects.toThrow(TrueForgeTypes.NotFoundError);
    });

    test("list_runs (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    automation_id: "automation_id",
                    created_at: "2024-01-15T09:30:00Z",
                    created_by_subject: {
                        subject_display_name: "subject_display_name",
                        subject_id: "subject_id",
                        subject_type: "subject_type",
                    },
                    event_ids: ["event_ids"],
                    finished_at: "2024-01-15T09:30:00Z",
                    id: "id",
                    lane_key: "lane_key",
                    mode: "shadow",
                    outcome: { key: "value" },
                    scheduled_for: "2024-01-15T09:30:00Z",
                    session_id: "session_id",
                    status: "coalescing",
                    subject_key: "subject_key",
                    triggered_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/api/v1/automations/automation_id/runs")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.automations.listRuns("automation_id");
        expect(response).toEqual({
            data: [
                {
                    automationId: "automation_id",
                    createdAt: new Date("2024-01-15T09:30:00.000Z"),
                    createdBySubject: {
                        subjectDisplayName: "subject_display_name",
                        subjectId: "subject_id",
                        subjectType: "subject_type",
                    },
                    eventIds: ["event_ids"],
                    finishedAt: new Date("2024-01-15T09:30:00.000Z"),
                    id: "id",
                    laneKey: "lane_key",
                    mode: "shadow",
                    outcome: {
                        key: "value",
                    },
                    scheduledFor: new Date("2024-01-15T09:30:00.000Z"),
                    sessionId: "session_id",
                    status: "coalescing",
                    subjectKey: "subject_key",
                    triggeredAt: new Date("2024-01-15T09:30:00.000Z"),
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                },
            ],
        });
    });

    test("list_runs (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/automations/automation_id/runs")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.automations.listRuns("automation_id");
        }).rejects.toThrow(TrueForgeTypes.ForbiddenError);
    });

    test("list_runs (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/automations/automation_id/runs")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.automations.listRuns("automation_id");
        }).rejects.toThrow(TrueForgeTypes.NotFoundError);
    });
});
