// This file was auto-generated by Fern from our API Definition.

import * as TrueForgeTypes from "../../src/api/index";
import { TrueForge } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EventsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    delivery_id: "delivery_id",
                    id: "id",
                    kind: "kind",
                    received_at: "2024-01-15T09:30:00Z",
                    routed_at: "2024-01-15T09:30:00Z",
                    source_id: "source_id",
                    source_kind: "github",
                    subject_key: "subject_key",
                    summary: { actor: null, label: null, number: null, repository: null, title: null },
                },
            ],
            pagination: { limit: 1, next_page_token: "next_page_token", previous_page_token: "previous_page_token" },
        };

        server
            .mockEndpoint({ once: false })
            .get("/api/v1/events")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            data: [
                {
                    deliveryId: "delivery_id",
                    id: "id",
                    kind: "kind",
                    receivedAt: new Date("2024-01-15T09:30:00.000Z"),
                    routedAt: new Date("2024-01-15T09:30:00.000Z"),
                    sourceId: "source_id",
                    sourceKind: "github",
                    subjectKey: "subject_key",
                    summary: {
                        actor: null,
                        label: null,
                        number: null,
                        repository: null,
                        title: null,
                    },
                },
            ],
            pagination: {
                limit: 1,
                nextPageToken: "next_page_token",
                previousPageToken: "previous_page_token",
            },
        };
        const page = await client.events.list();

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server.mockEndpoint().get("/api/v1/events").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.events.list();
        }).rejects.toThrow(TrueForgeTypes.BadRequestError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: {
                delivery_id: "delivery_id",
                id: "id",
                kind: "kind",
                payload: { key: "value" },
                received_at: "2024-01-15T09:30:00Z",
                routed_at: "2024-01-15T09:30:00Z",
                source_id: "source_id",
                source_kind: "github",
                subject_key: "subject_key",
                summary: { actor: "actor", label: "label", number: 1, repository: "repository", title: "title" },
            },
        };

        server
            .mockEndpoint()
            .get("/api/v1/events/event_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.events.get("event_id");
        expect(response).toEqual({
            data: {
                deliveryId: "delivery_id",
                id: "id",
                kind: "kind",
                payload: {
                    key: "value",
                },
                receivedAt: new Date("2024-01-15T09:30:00.000Z"),
                routedAt: new Date("2024-01-15T09:30:00.000Z"),
                sourceId: "source_id",
                sourceKind: "github",
                subjectKey: "subject_key",
                summary: {
                    actor: "actor",
                    label: "label",
                    number: 1,
                    repository: "repository",
                    title: "title",
                },
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/events/event_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.events.get("event_id");
        }).rejects.toThrow(TrueForgeTypes.NotFoundError);
    });
});
