// This file was auto-generated by Fern from our API Definition.

import * as TrueForgeTypes from "../../src/api/index";
import { TrueForge } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EventSourcesClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    created_at: "2024-01-15T09:30:00Z",
                    created_by_subject: {
                        subject_display_name: "subject_display_name",
                        subject_id: "subject_id",
                        subject_type: "subject_type",
                    },
                    id: "id",
                    kind: "github",
                    last_delivery_at: "2024-01-15T09:30:00Z",
                    manifest: { app: null, kind: "github" },
                    name: "name",
                    status: "pending",
                    updated_at: "2024-01-15T09:30:00Z",
                    webhook_url: "webhook_url",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/api/v1/event-sources")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.eventSources.list();
        expect(response).toEqual({
            data: [
                {
                    createdAt: new Date("2024-01-15T09:30:00.000Z"),
                    createdBySubject: {
                        subjectDisplayName: "subject_display_name",
                        subjectId: "subject_id",
                        subjectType: "subject_type",
                    },
                    id: "id",
                    kind: "github",
                    lastDeliveryAt: new Date("2024-01-15T09:30:00.000Z"),
                    manifest: {
                        app: null,
                        kind: "github",
                    },
                    name: "name",
                    status: "pending",
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                    webhookUrl: "webhook_url",
                },
            ],
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/event-sources")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.eventSources.list();
        }).rejects.toThrow(TrueForgeTypes.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/event-sources")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.eventSources.list();
        }).rejects.toThrow(TrueForgeTypes.ForbiddenError);
    });

    test("create_github_manifest (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            data: { action_url: "action_url", manifest: { key: "value" }, source_id: "source_id", state: "state" },
        };

        server
            .mockEndpoint()
            .post("/api/v1/event-sources/github/manifest")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.eventSources.createGithubManifest({
            name: "name",
        });
        expect(response).toEqual({
            data: {
                actionUrl: "action_url",
                manifest: {
                    key: "value",
                },
                sourceId: "source_id",
                state: "state",
            },
        });
    });

    test("create_github_manifest (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = { name: "xy" };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/api/v1/event-sources/github/manifest")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.eventSources.createGithubManifest({
                name: "xy",
            });
        }).rejects.toThrow(TrueForgeTypes.BadRequestError);
    });

    test("create_github_manifest (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });
        const rawRequestBody = { name: "xy" };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/api/v1/event-sources/github/manifest")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.eventSources.createGithubManifest({
                name: "xy",
            });
        }).rejects.toThrow(TrueForgeTypes.ConflictError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: {
                created_at: "2024-01-15T09:30:00Z",
                created_by_subject: {
                    subject_display_name: "subject_display_name",
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                },
                id: "id",
                kind: "github",
                last_delivery_at: "2024-01-15T09:30:00Z",
                manifest: {
                    app: { app_id: 1, app_slug: "app_slug", client_id: "client_id", html_url: "html_url", owner: null },
                    kind: "github",
                },
                name: "name",
                status: "pending",
                updated_at: "2024-01-15T09:30:00Z",
                webhook_url: "webhook_url",
            },
        };

        server
            .mockEndpoint()
            .get("/api/v1/event-sources/source_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.eventSources.get("source_id");
        expect(response).toEqual({
            data: {
                createdAt: new Date("2024-01-15T09:30:00.000Z"),
                createdBySubject: {
                    subjectDisplayName: "subject_display_name",
                    subjectId: "subject_id",
                    subjectType: "subject_type",
                },
                id: "id",
                kind: "github",
                lastDeliveryAt: new Date("2024-01-15T09:30:00.000Z"),
                manifest: {
                    app: {
                        appId: 1,
                        appSlug: "app_slug",
                        clientId: "client_id",
                        htmlUrl: "html_url",
                        owner: null,
                    },
                    kind: "github",
                },
                name: "name",
                status: "pending",
                updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                webhookUrl: "webhook_url",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/event-sources/source_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.eventSources.get("source_id");
        }).rejects.toThrow(TrueForgeTypes.NotFoundError);
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, token: "test", baseUrl: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/event-sources/source_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.eventSources.delete("source_id");
        expect(response).toEqual({});
    });
});
