// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AutomationMode } from "./AutomationMode.js";
import { AutomationStatus } from "./AutomationStatus.js";
import { ComponentsSchemasEventTrigger } from "./ComponentsSchemasEventTrigger.js";
import { LanePart } from "./LanePart.js";

export const AutomationManifest: core.serialization.ObjectSchema<
    serializers.AutomationManifest.Raw,
    TrueForge.AutomationManifest
> = core.serialization.object({
    coalesceSeconds: core.serialization.property("coalesce_seconds", core.serialization.number().optional()),
    emit: core.serialization.list(core.serialization.string()).optional(),
    lane: core.serialization.list(LanePart).optional(),
    mode: AutomationMode.optional(),
    status: AutomationStatus.optional(),
    task: core.serialization.string(),
    trigger: ComponentsSchemasEventTrigger,
});

export declare namespace AutomationManifest {
    export interface Raw {
        coalesce_seconds?: number | null;
        emit?: string[] | null;
        lane?: LanePart.Raw[] | null;
        mode?: AutomationMode.Raw | null;
        status?: AutomationStatus.Raw | null;
        task: string;
        trigger: ComponentsSchemasEventTrigger.Raw;
    }
}
