// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AutomationManifest } from "./AutomationManifest.js";
import { CreatedBySubject } from "./CreatedBySubject.js";
import { ResourceName } from "./ResourceName.js";

export const Automation: core.serialization.ObjectSchema<serializers.Automation.Raw, TrueForge.Automation> =
    core.serialization.object({
        agentName: core.serialization.property("agent_name", ResourceName),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        createdBySubject: core.serialization.property("created_by_subject", CreatedBySubject),
        id: core.serialization.string(),
        manifest: AutomationManifest,
        name: ResourceName,
        updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    });

export declare namespace Automation {
    export interface Raw {
        agent_name: ResourceName.Raw;
        created_at: string;
        created_by_subject: CreatedBySubject.Raw;
        id: string;
        manifest: AutomationManifest.Raw;
        name: ResourceName.Raw;
        updated_at: string;
    }
}
