// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AutomationMode: core.serialization.Schema<serializers.AutomationMode.Raw, TrueForge.AutomationMode> =
    core.serialization.enum_(["shadow", "armed"]);

export declare namespace AutomationMode {
    export type Raw = "shadow" | "armed";
}
