// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AutomationStatus: core.serialization.Schema<serializers.AutomationStatus.Raw, TrueForge.AutomationStatus> =
    core.serialization.enum_(["active", "paused"]);

export declare namespace AutomationStatus {
    export type Raw = "active" | "paused";
}
