// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AutomationRunStatus: core.serialization.Schema<
    serializers.AutomationRunStatus.Raw,
    TrueForge.AutomationRunStatus
> = core.serialization.enum_(["coalescing", "triggered", "waiting", "completed", "shadowed", "failed"]);

export declare namespace AutomationRunStatus {
    export type Raw = "coalescing" | "triggered" | "waiting" | "completed" | "shadowed" | "failed";
}
