// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AutomationMode } from "./AutomationMode.js";
import { AutomationRunStatus } from "./AutomationRunStatus.js";
import { CreatedBySubject } from "./CreatedBySubject.js";

export const AutomationRun: core.serialization.ObjectSchema<serializers.AutomationRun.Raw, TrueForge.AutomationRun> =
    core.serialization.object({
        automationId: core.serialization.property("automation_id", core.serialization.string()),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        createdBySubject: core.serialization.property("created_by_subject", CreatedBySubject),
        eventIds: core.serialization.property("event_ids", core.serialization.list(core.serialization.string())),
        finishedAt: core.serialization.property("finished_at", core.serialization.date().nullable()),
        id: core.serialization.string(),
        laneKey: core.serialization.property("lane_key", core.serialization.string().nullable()),
        mode: AutomationMode,
        outcome: core.serialization.record(core.serialization.string(), core.serialization.unknown()).nullable(),
        scheduledFor: core.serialization.property("scheduled_for", core.serialization.date()),
        sessionId: core.serialization.property("session_id", core.serialization.string().nullable()),
        status: AutomationRunStatus,
        subjectKey: core.serialization.property("subject_key", core.serialization.string()),
        triggeredAt: core.serialization.property("triggered_at", core.serialization.date().nullable()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    });

export declare namespace AutomationRun {
    export interface Raw {
        automation_id: string;
        created_at: string;
        created_by_subject: CreatedBySubject.Raw;
        event_ids: string[];
        finished_at?: string | null;
        id: string;
        lane_key?: string | null;
        mode: AutomationMode.Raw;
        outcome?: Record<string, unknown> | null;
        scheduled_for: string;
        session_id?: string | null;
        status: AutomationRunStatus.Raw;
        subject_key: string;
        triggered_at?: string | null;
        updated_at: string;
    }
}
