// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import type * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EventTrigger } from "./EventTrigger.js";

export const ComponentsSchemasEventTrigger: core.serialization.ObjectSchema<
    serializers.ComponentsSchemasEventTrigger.Raw,
    TrueForge.ComponentsSchemasEventTrigger
> = EventTrigger;

export declare namespace ComponentsSchemasEventTrigger {
    export type Raw = EventTrigger.Raw;
}
