// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConditionOperator } from "./ConditionOperator.js";
import { ConditionValue } from "./ConditionValue.js";

export const Condition: core.serialization.ObjectSchema<serializers.Condition.Raw, TrueForge.Condition> =
    core.serialization.object({
        field: core.serialization.string(),
        op: ConditionOperator,
        value: ConditionValue.optional(),
    });

export declare namespace Condition {
    export interface Raw {
        field: string;
        op: ConditionOperator.Raw;
        value?: ConditionValue.Raw | null;
    }
}
