// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ConditionOperator: core.serialization.Schema<
    serializers.ConditionOperator.Raw,
    TrueForge.ConditionOperator
> = core.serialization.enum_(["eq", "neq", "in", "not_in", "contains", "exists", "not_exists"]);

export declare namespace ConditionOperator {
    export type Raw = "eq" | "neq" | "in" | "not_in" | "contains" | "exists" | "not_exists";
}
