// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ConditionValueThreeItem: core.serialization.Schema<
    serializers.ConditionValueThreeItem.Raw,
    TrueForge.ConditionValueThreeItem
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.number()]);

export declare namespace ConditionValueThreeItem {
    export type Raw = string | number;
}
