// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConditionValueThreeItem } from "./ConditionValueThreeItem.js";

export const ConditionValue: core.serialization.Schema<serializers.ConditionValue.Raw, TrueForge.ConditionValue> =
    core.serialization.undiscriminatedUnion([
        core.serialization.string(),
        core.serialization.number(),
        core.serialization.boolean(),
        core.serialization.list(ConditionValueThreeItem),
    ]);

export declare namespace ConditionValue {
    export type Raw = string | number | boolean | ConditionValueThreeItem.Raw[];
}
