// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GithubManifestStart } from "./GithubManifestStart.js";

export const CreateGithubManifestResponse: core.serialization.ObjectSchema<
    serializers.CreateGithubManifestResponse.Raw,
    TrueForge.CreateGithubManifestResponse
> = core.serialization.object({
    data: GithubManifestStart,
});

export declare namespace CreateGithubManifestResponse {
    export interface Raw {
        data: GithubManifestStart.Raw;
    }
}
