// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DeleteAutomationResponse: core.serialization.ObjectSchema<
    serializers.DeleteAutomationResponse.Raw,
    TrueForge.DeleteAutomationResponse
> = core.serialization.object({});

export declare namespace DeleteAutomationResponse {
    export type Raw = {};
}
