// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DeleteEventSourceResponse: core.serialization.ObjectSchema<
    serializers.DeleteEventSourceResponse.Raw,
    TrueForge.DeleteEventSourceResponse
> = core.serialization.object({});

export declare namespace DeleteEventSourceResponse {
    export type Raw = {};
}
