// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EventSourceManifestApp } from "./EventSourceManifestApp.js";
import { EventSourceManifestOne } from "./EventSourceManifestOne.js";

export const EventSourceManifest: core.serialization.Schema<
    serializers.EventSourceManifest.Raw,
    TrueForge.EventSourceManifest
> = core.serialization.undiscriminatedUnion([EventSourceManifestApp, EventSourceManifestOne]);

export declare namespace EventSourceManifest {
    export type Raw = EventSourceManifestApp.Raw | EventSourceManifestOne.Raw;
}
