// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CreatedBySubject } from "./CreatedBySubject.js";
import { EventSourceKind } from "./EventSourceKind.js";
import { EventSourceManifest } from "./EventSourceManifest.js";
import { EventSourceStatus } from "./EventSourceStatus.js";
import { ResourceName } from "./ResourceName.js";

export const EventSource: core.serialization.ObjectSchema<serializers.EventSource.Raw, TrueForge.EventSource> =
    core.serialization.object({
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        createdBySubject: core.serialization.property("created_by_subject", CreatedBySubject),
        id: core.serialization.string(),
        kind: EventSourceKind,
        lastDeliveryAt: core.serialization.property("last_delivery_at", core.serialization.date().nullable()),
        manifest: EventSourceManifest,
        name: ResourceName,
        status: EventSourceStatus,
        updatedAt: core.serialization.property("updated_at", core.serialization.date()),
        webhookUrl: core.serialization.property("webhook_url", core.serialization.string()),
    });

export declare namespace EventSource {
    export interface Raw {
        created_at: string;
        created_by_subject: CreatedBySubject.Raw;
        id: string;
        kind: EventSourceKind.Raw;
        last_delivery_at?: string | null;
        manifest: EventSourceManifest.Raw;
        name: ResourceName.Raw;
        status: EventSourceStatus.Raw;
        updated_at: string;
        webhook_url: string;
    }
}
