// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EventSourceKind: core.serialization.Schema<serializers.EventSourceKind.Raw, TrueForge.EventSourceKind> =
    core.serialization.stringLiteral("github");

export declare namespace EventSourceKind {
    export type Raw = "github";
}
