// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EventSourceKind } from "./EventSourceKind.js";
import { EventSummary } from "./EventSummary.js";

export const EventDetail: core.serialization.ObjectSchema<serializers.EventDetail.Raw, TrueForge.EventDetail> =
    core.serialization.object({
        deliveryId: core.serialization.property("delivery_id", core.serialization.string()),
        id: core.serialization.string(),
        kind: core.serialization.string(),
        payload: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
        receivedAt: core.serialization.property("received_at", core.serialization.date()),
        routedAt: core.serialization.property("routed_at", core.serialization.date().nullable()),
        sourceId: core.serialization.property("source_id", core.serialization.string()),
        sourceKind: core.serialization.property("source_kind", EventSourceKind),
        subjectKey: core.serialization.property("subject_key", core.serialization.string()),
        summary: EventSummary,
    });

export declare namespace EventDetail {
    export interface Raw {
        delivery_id: string;
        id: string;
        kind: string;
        payload: Record<string, unknown>;
        received_at: string;
        routed_at?: string | null;
        source_id: string;
        source_kind: EventSourceKind.Raw;
        subject_key: string;
        summary: EventSummary.Raw;
    }
}
