// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EventSourceStatus: core.serialization.Schema<
    serializers.EventSourceStatus.Raw,
    TrueForge.EventSourceStatus
> = core.serialization.enum_(["pending", "active", "error"]);

export declare namespace EventSourceStatus {
    export type Raw = "pending" | "active" | "error";
}
