// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EventSummary: core.serialization.ObjectSchema<serializers.EventSummary.Raw, TrueForge.EventSummary> =
    core.serialization.object({
        actor: core.serialization.string().nullable(),
        label: core.serialization.string().nullable(),
        number: core.serialization.number().nullable(),
        repository: core.serialization.string().nullable(),
        title: core.serialization.string().nullable(),
    });

export declare namespace EventSummary {
    export interface Raw {
        actor?: string | null;
        label?: string | null;
        number?: number | null;
        repository?: string | null;
        title?: string | null;
    }
}
