// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { When } from "./When.js";

export const EventTrigger: core.serialization.ObjectSchema<serializers.EventTrigger.Raw, TrueForge.EventTrigger> =
    core.serialization.object({
        kind: core.serialization.string(),
        sourceId: core.serialization.property("source_id", core.serialization.string()),
        type: core.serialization.stringLiteral("event"),
        when: When.optional(),
    });

export declare namespace EventTrigger {
    export interface Raw {
        kind: string;
        source_id: string;
        type: "event";
        when?: When.Raw | null;
    }
}
