// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GithubAppConfig } from "./GithubAppConfig.js";

export const EventSourceManifest: core.serialization.ObjectSchema<
    serializers.EventSourceManifest.Raw,
    TrueForge.EventSourceManifest
> = core.serialization.object({
    app: GithubAppConfig.nullable(),
    kind: core.serialization.stringLiteral("github"),
});

export declare namespace EventSourceManifest {
    export interface Raw {
        app?: GithubAppConfig.Raw | null;
        kind: "github";
    }
}
