// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Automation } from "./Automation.js";

export const GetAutomationResponse: core.serialization.ObjectSchema<
    serializers.GetAutomationResponse.Raw,
    TrueForge.GetAutomationResponse
> = core.serialization.object({
    data: Automation,
});

export declare namespace GetAutomationResponse {
    export interface Raw {
        data: Automation.Raw;
    }
}
