// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EventDetail } from "./EventDetail.js";

export const GetEventResponse: core.serialization.ObjectSchema<
    serializers.GetEventResponse.Raw,
    TrueForge.GetEventResponse
> = core.serialization.object({
    data: EventDetail,
});

export declare namespace GetEventResponse {
    export interface Raw {
        data: EventDetail.Raw;
    }
}
