// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EventSource } from "./EventSource.js";

export const GetEventSourceResponse: core.serialization.ObjectSchema<
    serializers.GetEventSourceResponse.Raw,
    TrueForge.GetEventSourceResponse
> = core.serialization.object({
    data: EventSource,
});

export declare namespace GetEventSourceResponse {
    export interface Raw {
        data: EventSource.Raw;
    }
}
