// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const GithubManifestStart: core.serialization.ObjectSchema<
    serializers.GithubManifestStart.Raw,
    TrueForge.GithubManifestStart
> = core.serialization.object({
    actionUrl: core.serialization.property("action_url", core.serialization.string()),
    manifest: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    sourceId: core.serialization.property("source_id", core.serialization.string()),
    state: core.serialization.string(),
});

export declare namespace GithubManifestStart {
    export interface Raw {
        action_url: string;
        manifest: Record<string, unknown>;
        source_id: string;
        state: string;
    }
}
