// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const GithubAppConfig: core.serialization.ObjectSchema<
    serializers.GithubAppConfig.Raw,
    TrueForge.GithubAppConfig
> = core.serialization.object({
    appId: core.serialization.property("app_id", core.serialization.number()),
    appSlug: core.serialization.property("app_slug", core.serialization.string()),
    clientId: core.serialization.property("client_id", core.serialization.string()),
    htmlUrl: core.serialization.property("html_url", core.serialization.string()),
    owner: core.serialization.string().nullable(),
});

export declare namespace GithubAppConfig {
    export interface Raw {
        app_id: number;
        app_slug: string;
        client_id: string;
        html_url: string;
        owner?: string | null;
    }
}
