// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const LanePartPath: core.serialization.ObjectSchema<serializers.LanePartPath.Raw, TrueForge.LanePartPath> =
    core.serialization.object({
        path: core.serialization.string(),
        type: core.serialization.stringLiteral("field"),
    });

export declare namespace LanePartPath {
    export interface Raw {
        path: string;
        type: "field";
    }
}
