// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { LanePartPath } from "./LanePartPath.js";
import { LanePartValue } from "./LanePartValue.js";

export const LanePart: core.serialization.Schema<serializers.LanePart.Raw, TrueForge.LanePart> =
    core.serialization.undiscriminatedUnion([LanePartPath, LanePartValue]);

export declare namespace LanePart {
    export type Raw = LanePartPath.Raw | LanePartValue.Raw;
}
