// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const LanePartValue: core.serialization.ObjectSchema<serializers.LanePartValue.Raw, TrueForge.LanePartValue> =
    core.serialization.object({
        type: core.serialization.stringLiteral("literal"),
        value: core.serialization.string(),
    });

export declare namespace LanePartValue {
    export interface Raw {
        type: "literal";
        value: string;
    }
}
