// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EventSource } from "./EventSource.js";

export const ListEventSourcesResponse: core.serialization.ObjectSchema<
    serializers.ListEventSourcesResponse.Raw,
    TrueForge.ListEventSourcesResponse
> = core.serialization.object({
    data: core.serialization.list(EventSource),
});

export declare namespace ListEventSourcesResponse {
    export interface Raw {
        data: EventSource.Raw[];
    }
}
