// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Event } from "./Event.js";
import { TokenPagination } from "./TokenPagination.js";

export const ListEventsResponse: core.serialization.ObjectSchema<
    serializers.ListEventsResponse.Raw,
    TrueForge.ListEventsResponse
> = core.serialization.object({
    data: core.serialization.list(Event),
    pagination: TokenPagination,
});

export declare namespace ListEventsResponse {
    export interface Raw {
        data: Event.Raw[];
        pagination: TokenPagination.Raw;
    }
}
