// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Automation } from "./Automation.js";
import { TokenPagination } from "./TokenPagination.js";

export const ListAutomationsResponse: core.serialization.ObjectSchema<
    serializers.ListAutomationsResponse.Raw,
    TrueForge.ListAutomationsResponse
> = core.serialization.object({
    data: core.serialization.list(Automation),
    pagination: TokenPagination,
});

export declare namespace ListAutomationsResponse {
    export interface Raw {
        data: Automation.Raw[];
        pagination: TokenPagination.Raw;
    }
}
