// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AutomationRun } from "./AutomationRun.js";

export const ReplayAutomationResponse: core.serialization.ObjectSchema<
    serializers.ReplayAutomationResponse.Raw,
    TrueForge.ReplayAutomationResponse
> = core.serialization.object({
    data: AutomationRun,
});

export declare namespace ReplayAutomationResponse {
    export interface Raw {
        data: AutomationRun.Raw;
    }
}
