// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Condition } from "./Condition.js";

export const When: core.serialization.ObjectSchema<serializers.When.Raw, TrueForge.When> = core.serialization.object({
    all: core.serialization.list(Condition).optional(),
});

export declare namespace When {
    export interface Raw {
        all?: Condition.Raw[] | null;
    }
}
