// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListEventsRequest {
    /** Page size. Defaults to 25 */
    limit?: number;
    /** Opaque token from a previous response `next_page_token`. */
    pageToken?: string;
    /** Only events from this source. */
    sourceId?: string;
    /** Only events of this connector kind, e.g. `issues.labeled`. */
    kind?: string;
    /** Only events about this subject, e.g. `owner/repo#61`. */
    subjectKey?: string;
    /** Only events received at or after this instant. */
    since?: Date;
}
