// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreateGithubManifestRequest: core.serialization.Schema<
    serializers.CreateGithubManifestRequest.Raw,
    TrueForge.CreateGithubManifestRequest
> = core.serialization.object({
    name: core.serialization.string(),
    owner: core.serialization.string().optional(),
});

export declare namespace CreateGithubManifestRequest {
    export interface Raw {
        name: string;
        owner?: string | null;
    }
}
