// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface CreateGithubManifestRequest {
    /** Source name, unique per tenant. Also used as the App name suffix. */
    name: string;
    /** Organization login to create the App under. Omit to create it under the calling user. */
    owner?: string;
}
