// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { AutomationManifest } from "../../../../types/AutomationManifest.js";
import { ResourceName } from "../../../../types/ResourceName.js";

export const CreateAutomationRequest: core.serialization.Schema<
    serializers.CreateAutomationRequest.Raw,
    TrueForge.CreateAutomationRequest
> = core.serialization.object({
    agentName: core.serialization.property("agent_name", ResourceName),
    manifest: AutomationManifest,
    name: ResourceName,
});

export declare namespace CreateAutomationRequest {
    export interface Raw {
        agent_name: ResourceName.Raw;
        manifest: AutomationManifest.Raw;
        name: ResourceName.Raw;
    }
}
