// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const ReplayAutomationRequest: core.serialization.Schema<
    serializers.ReplayAutomationRequest.Raw,
    TrueForge.ReplayAutomationRequest
> = core.serialization.object({
    eventId: core.serialization.property("event_id", core.serialization.string()),
});

export declare namespace ReplayAutomationRequest {
    export interface Raw {
        event_id: string;
    }
}
