// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { AutomationManifest } from "../../../../types/AutomationManifest.js";
import { ResourceName } from "../../../../types/ResourceName.js";

export const UpdateAutomationRequest: core.serialization.Schema<
    serializers.UpdateAutomationRequest.Raw,
    TrueForge.UpdateAutomationRequest
> = core.serialization.object({
    manifest: AutomationManifest,
    name: ResourceName,
});

export declare namespace UpdateAutomationRequest {
    export interface Raw {
        manifest: AutomationManifest.Raw;
        name: ResourceName.Raw;
    }
}
