// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as serializers from "../../../../serialization/index.js";
import * as TrueForge from "../../../index.js";

export declare namespace AutomationsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AutomationsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AutomationsClient.Options>;

    constructor(options: AutomationsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * List automations for the tenant, newest first. Optionally filter by `agent_names`.
     *
     * @param {TrueForge.ListAutomationsRequest} request
     * @param {AutomationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueForge.BadRequestError}
     * @throws {@link errors.TrueForgeError}
     * @throws {@link errors.TrueForgeTimeoutError}
     *
     * @example
     *     await client.automations.list()
     */
    public async list(
        request: TrueForge.ListAutomationsRequest = {},
        requestOptions?: AutomationsClient.RequestOptions,
    ): Promise<core.Page<TrueForge.Automation, TrueForge.ListAutomationsResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: TrueForge.ListAutomationsRequest,
            ): Promise<core.WithRawResponse<TrueForge.ListAutomationsResponse>> => {
                const { limit = 25, pageToken, agentNames } = request;
                const _queryParams: Record<string, unknown> = {
                    limit,
                    page_token: pageToken,
                    agent_names: agentNames,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)),
                        "api/v1/automations",
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: serializers.ListAutomationsResponse.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new TrueForge.BadRequestError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.TrueForgeError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/automations");
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<TrueForge.Automation, TrueForge.ListAutomationsResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.pagination.nextPageToken != null &&
                !(typeof response?.pagination.nextPageToken === "string" && response?.pagination.nextPageToken === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "pageToken", response?.pagination.nextPageToken));
            },
        });
    }

    /**
     * Bind an agent to an event trigger. The automation starts in the mode its manifest declares (shadow by default).
     *
     * @param {TrueForge.CreateAutomationRequest} request
     * @param {AutomationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueForge.BadRequestError}
     * @throws {@link TrueForge.NotFoundError}
     * @throws {@link TrueForge.ConflictError}
     * @throws {@link errors.TrueForgeError}
     * @throws {@link errors.TrueForgeTimeoutError}
     *
     * @example
     *     await client.automations.create({
     *         agentName: "agent_name",
     *         manifest: {
     *             task: "task",
     *             trigger: {
     *                 kind: "kind",
     *                 sourceId: "source_id",
     *                 type: "event"
     *             }
     *         },
     *         name: "name"
     *     })
     */
    public create(
        request: TrueForge.CreateAutomationRequest,
        requestOptions?: AutomationsClient.RequestOptions,
    ): core.HttpResponsePromise<TrueForge.GetAutomationResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: TrueForge.CreateAutomationRequest,
        requestOptions?: AutomationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<TrueForge.GetAutomationResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "api/v1/automations",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(
                serializers.CreateAutomationRequest.jsonOrThrow(request, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    omitUndefined: true,
                }),
                requestOptions?.additionalBodyParameters,
            ),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.GetAutomationResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TrueForge.BadRequestError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new TrueForge.NotFoundError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 409:
                    throw new TrueForge.ConflictError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueForgeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/v1/automations");
    }

    /**
     * Fetch one automation by id.
     *
     * @param {string} automation_id - Immutable automation identifier.
     * @param {AutomationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueForge.ForbiddenError}
     * @throws {@link TrueForge.NotFoundError}
     * @throws {@link errors.TrueForgeError}
     * @throws {@link errors.TrueForgeTimeoutError}
     *
     * @example
     *     await client.automations.get("automation_id")
     */
    public get(
        automation_id: string,
        requestOptions?: AutomationsClient.RequestOptions,
    ): core.HttpResponsePromise<TrueForge.GetAutomationResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(automation_id, requestOptions));
    }

    private async __get(
        automation_id: string,
        requestOptions?: AutomationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<TrueForge.GetAutomationResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api/v1/automations/${core.url.encodePathParam(automation_id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.GetAutomationResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new TrueForge.ForbiddenError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new TrueForge.NotFoundError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueForgeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/automations/{automation_id}",
        );
    }

    /**
     * Replace the name and manifest. Open coalesce windows keep their original settings.
     *
     * @param {string} automation_id - Immutable automation identifier.
     * @param {TrueForge.UpdateAutomationRequest} request
     * @param {AutomationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueForge.BadRequestError}
     * @throws {@link TrueForge.ForbiddenError}
     * @throws {@link TrueForge.NotFoundError}
     * @throws {@link TrueForge.ConflictError}
     * @throws {@link errors.TrueForgeError}
     * @throws {@link errors.TrueForgeTimeoutError}
     *
     * @example
     *     await client.automations.update("automation_id", {
     *         manifest: {
     *             task: "task",
     *             trigger: {
     *                 kind: "kind",
     *                 sourceId: "source_id",
     *                 type: "event"
     *             }
     *         },
     *         name: "name"
     *     })
     */
    public update(
        automation_id: string,
        request: TrueForge.UpdateAutomationRequest,
        requestOptions?: AutomationsClient.RequestOptions,
    ): core.HttpResponsePromise<TrueForge.GetAutomationResponse> {
        return core.HttpResponsePromise.fromPromise(this.__update(automation_id, request, requestOptions));
    }

    private async __update(
        automation_id: string,
        request: TrueForge.UpdateAutomationRequest,
        requestOptions?: AutomationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<TrueForge.GetAutomationResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api/v1/automations/${core.url.encodePathParam(automation_id)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(
                serializers.UpdateAutomationRequest.jsonOrThrow(request, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    omitUndefined: true,
                }),
                requestOptions?.additionalBodyParameters,
            ),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.GetAutomationResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TrueForge.BadRequestError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 403:
                    throw new TrueForge.ForbiddenError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new TrueForge.NotFoundError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 409:
                    throw new TrueForge.ConflictError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueForgeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/api/v1/automations/{automation_id}",
        );
    }

    /**
     * Delete an automation and its run history. Sessions already started keep running.
     *
     * @param {string} automation_id - Immutable automation identifier.
     * @param {AutomationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueForge.ForbiddenError}
     * @throws {@link errors.TrueForgeError}
     * @throws {@link errors.TrueForgeTimeoutError}
     *
     * @example
     *     await client.automations.delete("automation_id")
     */
    public delete(
        automation_id: string,
        requestOptions?: AutomationsClient.RequestOptions,
    ): core.HttpResponsePromise<TrueForge.DeleteAutomationResponse> {
        return core.HttpResponsePromise.fromPromise(this.__delete(automation_id, requestOptions));
    }

    private async __delete(
        automation_id: string,
        requestOptions?: AutomationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<TrueForge.DeleteAutomationResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api/v1/automations/${core.url.encodePathParam(automation_id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.DeleteAutomationResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new TrueForge.ForbiddenError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueForgeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/api/v1/automations/{automation_id}",
        );
    }

    /**
     * Run the automation against one recorded event in shadow mode: the agent pauses before its first gated tool call and nothing is written. Returns the run, which the dispatch loop picks up immediately.
     *
     * @param {string} automation_id - Immutable automation identifier.
     * @param {TrueForge.ReplayAutomationRequest} request
     * @param {AutomationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueForge.BadRequestError}
     * @throws {@link TrueForge.ForbiddenError}
     * @throws {@link TrueForge.NotFoundError}
     * @throws {@link errors.TrueForgeError}
     * @throws {@link errors.TrueForgeTimeoutError}
     *
     * @example
     *     await client.automations.replay("automation_id", {
     *         eventId: "event_id"
     *     })
     */
    public replay(
        automation_id: string,
        request: TrueForge.ReplayAutomationRequest,
        requestOptions?: AutomationsClient.RequestOptions,
    ): core.HttpResponsePromise<TrueForge.ReplayAutomationResponse> {
        return core.HttpResponsePromise.fromPromise(this.__replay(automation_id, request, requestOptions));
    }

    private async __replay(
        automation_id: string,
        request: TrueForge.ReplayAutomationRequest,
        requestOptions?: AutomationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<TrueForge.ReplayAutomationResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api/v1/automations/${core.url.encodePathParam(automation_id)}/replay`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(
                serializers.ReplayAutomationRequest.jsonOrThrow(request, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    omitUndefined: true,
                }),
                requestOptions?.additionalBodyParameters,
            ),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.ReplayAutomationResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TrueForge.BadRequestError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 403:
                    throw new TrueForge.ForbiddenError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new TrueForge.NotFoundError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueForgeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/automations/{automation_id}/replay",
        );
    }

    /**
     * Runs of one automation, newest first: open coalesce windows and finished runs alike.
     *
     * @param {string} automation_id - Immutable automation identifier.
     * @param {AutomationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueForge.ForbiddenError}
     * @throws {@link TrueForge.NotFoundError}
     * @throws {@link errors.TrueForgeError}
     * @throws {@link errors.TrueForgeTimeoutError}
     *
     * @example
     *     await client.automations.listRuns("automation_id")
     */
    public listRuns(
        automation_id: string,
        requestOptions?: AutomationsClient.RequestOptions,
    ): core.HttpResponsePromise<TrueForge.ListAutomationRunsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listRuns(automation_id, requestOptions));
    }

    private async __listRuns(
        automation_id: string,
        requestOptions?: AutomationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<TrueForge.ListAutomationRunsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api/v1/automations/${core.url.encodePathParam(automation_id)}/runs`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.ListAutomationRunsResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new TrueForge.ForbiddenError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new TrueForge.NotFoundError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueForgeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/automations/{automation_id}/runs",
        );
    }
}
